/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  //coreSidebar: [{type: 'autogenerated', dirName: 'smart-contract-modules'}]

  // But you can create a sidebar manually
  
  // tutorialSidebar: [
  //   'intro',
  //   'smart-contract-modules/README',
  //   'smart-contract-modules/dai-module/README',
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  // ],
  
};

module.exports = sidebars;
